services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: learning-platform-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./learning-platform-backend
    env_file:
      - ./learning-platform-backend/.env
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/learning-platform-backend
    depends_on:
      - db

  frontend:
    build: ./learning-platform-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  pgdata:
