version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: learning-platform-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./learning-platform-backend
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./learning-platform-backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./learning-platform-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    volumes:
      - ./learning-platform-frontend:/app
    restart: unless-stopped

volumes:
  pgdata:
